# Joystick Configuration
# Use joystick_identify node to figure out which axis does what

# strafe, drive_forward, yaw, pitch, up, down

# https://docs.ros.org/en/humble/p/joy/

thruster_control:
  - axis: "strafe"
    input: 0
    invert: true
    sensitivity: 1
    scale: "exponential"

  - axis: "drive_forward"
    input: 1 # num# of analog input. Find out from tuner node
    invert: false # to invert the axis
    sensitivity: 1 # more = more sensitive. keep it > 0
    scale: "exponential" # one of linear, logarithmic, exponential

  - axis: "yaw"
    input: 3
    invert: false
    sensitivity: 1
    scale: "exponential"

  - axis: "pitch"
    input: 4
    invert: true
    sensitivity: 1
    scale: "exponential"

  - axis: "up"
    input: 2
    invert: false
    sensitivity: 1
    scale: "exponential"

  - axis: "down"
    input: 5
    invert: false
    sensitivity: 1
    scale: "exponential"

  - button: "A"
    input: 1
    invert: false

  - button: "roll_left"
    input: 4
    invert: false

  - button: "roll_right"
    input: 5
    invert: false

  - button: "stabilize_toggle"
    input: 1
    invert: false

  - button: "expo_toggle"
    input: 2
    invert: false

  - button: "precision_toggle"
    input: 0
    invert: false

arm_control:
  - axis: "base_yaw_input" # Base rotate left right
    input: 3
    invert: false
    sensitivity: 1
    scale: "linear"

  - axis: "base_pitch_input" # Base up and down
    input: 4
    invert: false
    sensitivity: 1
    scale: "linear"

  - axis: "elbow_pitch_input" # Elbow
    input: 1
    invert: false
    sensitivity: 1
    scale: "linear"

  - axis: "wrist_yaw_input" # Wrist Rotation
    input: 0
    invert: false
    sensitivity: 1
    scale: "linear"

  - button: "claw_open_input" # Wrist up
    input: 4 # bumper
    invert: false

  - button: "claw_close_input" # Wrist down
    input: 5 # bumper
    invert: false

  - axis: "wrist_up_input" # Claw open
    input: 2 # left trigger
    invert: true
    sensitivity: 1
    scale: "linear"

  - axis: "wrist_down_input" # Claw close
    input: 5 # right trigger
    invert: true
    sensitivity: 1
    scale: "linear"
